version: 2

jobs:
  htmllint:
    docker:
      - image: kakakakakku/htmllint-cli
    steps:
      - checkout
      - run:
          htmllint  ./answer/example/HTML/01_helloTable/helloTable.html
      - run: 
          htmllint  ./answer/example/HTML/02_anchor/anchor.html
  stylelint:
    docker:
      - image: circleci/node:12.3.1
    steps:
      - checkout
      - run:
          name:
            install modules
          command: 
            npm install stylelint stylelint-config-standard --save-dev
      - run: 
          name: 
            Test CSS/01
          command:
            ./node_modules/.bin/stylelint answer/example/CSS/01_centerDiv/
      - run: 
          name: 
            Test CSS/02
          command:
            ./node_modules/.bin/stylelint answer/example/CSS/02_shadow/
          when:
            always
      - run: 
          name: 
            Test CSS/03
          command:
            ./node_modules/.bin/stylelint answer/example/CSS/03_nav/
          when:
            always

workflows:
  version: 2
  ci:
    jobs:
      - htmllint
      - stylelint