version: 2

jobs:
  htmllint:
    docker:
      - image: kakakakakku/htmllint-cli
    steps:
      - checkout
      - run: htmllint  ./answer/example/HTML/01_helloTable/helloTable.html

workflows:
  version: 2
  ci:
    jobs:
      - htmllint